### ISSUE TITLE
Lurker suggestions

### ISSUE THREAD

**Issue by moviemovieH** [tony12288221/fishtankExtension#1]
Love the extension, suggestions but not criticisms, potential quality of life improvements:

- Add a "hide" button next to "expand" button or add an "x" to close individual feeds
- Have the feeds re-scale to fill out the webpage when less feeds are active (i.e. 4 feeds would be in a 2x2 format and change aspect ratio to fill the screen space)
- Add ability to resize individual feeds or select from a scale preset (125/150/175% size aspect ratio)
- Offset the feed selection list to either left or right side of the screen, centered, or extended horizontally along the header 

It would be nice if there were only 4 feeds being used for example, or 6, or 9, that they would automatically scale their aspect ratio in preview to fill out the webpage (2x2, 2x3, 3x3 respectively) so there isn't as much empty webpage and the feeds being utilized will cover the screen. Love the extension, you're doing what the mde crew can't or choose not to.

**Comment by tony12288221** [comment]
I'm really glad to hear you like the extension! 

I can definitely add the first two bullets. I also added a feature to custom select how many columns used (with an auto option).

For the third bullet, I will implement a similar feature (i.e. how many columns the video player takes up), since I'm still learning html/js. It's not too pretty but it works lol.

Can you elaborate on the four bullet? I'm not sure what you mean.

I'll push the new update later tonight.

**Comment by moviemovieH** [comment]
Awesome thanks for the response! And after rereading it to myself I can see how poorly worded I was on my final point sorry. When you open the "display options" menu to show the feed selection list, its very intrusive and butts all the feeds down the webpage.  Personally I think it would be better if the selection list was a drop-down menu on either side of the page, instead of at the top.

**Comment by tony12288221** [comment]
Done. Let me know if there's any bugs I didn't find.
